// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Returns 200 if DB is reachable, 503 otherwise",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/locomotives": {
            "get": {
                "description": "Returns all locomotives with their current status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "locomotives"
                ],
                "summary": "List all locomotives",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Locomotive"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/locomotives/{id}": {
            "get": {
                "description": "Returns a single locomotive by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "locomotives"
                ],
                "summary": "Get locomotive by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Locomotive"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/locomotives/{id}/alerts": {
            "get": {
                "description": "Returns alerts for a locomotive. Filter by active status and/or severity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "List alerts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Only unacknowledged alerts",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by severity: warning or critical",
                        "name": "severity",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Alert"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/locomotives/{id}/alerts/{alert_id}/acknowledge": {
            "post": {
                "description": "Marks an alert as acknowledged by the dispatcher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Acknowledge an alert",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Alert ID",
                        "name": "alert_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Acknowledger name",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "acknowledged_by": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/locomotives/{id}/events": {
            "get": {
                "description": "Returns manual events (incidents, maintenance notes) for a locomotive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "List events",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339), default: 1h ago",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339), default: now",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Event"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Records a manual event (incident, maintenance, note) for a locomotive",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Create manual event",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event payload",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Event"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/locomotives/{id}/export/csv": {
            "get": {
                "description": "Downloads a CSV file containing historical telemetry for a locomotive",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Export telemetry as CSV",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339), default: 1h ago",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339), default: now",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CSV file",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/locomotives/{id}/health/history": {
            "get": {
                "description": "Returns health snapshot history for a locomotive, downsampled to 1 point per minute",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get health score history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339), default: 1h ago",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339), default: now",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.HealthSnapshot"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/locomotives/{id}/limits": {
            "get": {
                "description": "Returns all warning and critical thresholds configured for a locomotive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Get telemetry limits",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TelemetryLimits"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Updates warning and critical thresholds for a locomotive (takes effect immediately)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Update telemetry limits",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Limits payload",
                        "name": "limits",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.TelemetryLimits"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/locomotives/{id}/telemetry/current": {
            "get": {
                "description": "Returns the latest telemetry snapshot for a locomotive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Get current telemetry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Telemetry"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/locomotives/{id}/telemetry/history": {
            "get": {
                "description": "Returns historical telemetry records for a locomotive within a time range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Get telemetry history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Locomotive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339), default: 1h ago",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339), default: now",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max records (default 1000)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Telemetry"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Alert": {
            "type": "object",
            "properties": {
                "acknowledged_at": {
                    "type": "string"
                },
                "acknowledged_by": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_acknowledged": {
                    "type": "boolean"
                },
                "locomotive_id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "parameter_name": {
                    "type": "string"
                },
                "resolved_at": {
                    "type": "string"
                },
                "severity": {
                    "description": "warning | critical",
                    "type": "string"
                },
                "threshold_value": {
                    "type": "number"
                },
                "ts": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "domain.Event": {
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "event_type": {
                    "description": "incident | maintenance | note | replay_mark",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "locomotive_id": {
                    "type": "integer"
                },
                "telemetry_snapshot": {
                    "type": "object"
                },
                "ts": {
                    "type": "string"
                }
            }
        },
        "domain.HealthSnapshot": {
            "type": "object",
            "properties": {
                "health_score": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "locomotive_id": {
                    "type": "integer"
                },
                "top_factors": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "ts": {
                    "type": "string"
                }
            }
        },
        "domain.Locomotive": {
            "type": "object",
            "properties": {
                "depot": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "power_type": {
                    "description": "diesel | electric",
                    "type": "string"
                },
                "status": {
                    "description": "active | maintenance",
                    "type": "string"
                },
                "type": {
                    "description": "cargo | passenger",
                    "type": "string"
                },
                "year_built": {
                    "type": "integer"
                }
            }
        },
        "domain.Telemetry": {
            "type": "object",
            "properties": {
                "ambient_temp": {
                    "type": "number"
                },
                "battery_voltage": {
                    "type": "number"
                },
                "brake_cylinder_pressure": {
                    "type": "number"
                },
                "brake_pipe_pressure": {
                    "type": "number"
                },
                "engine_rpm": {
                    "type": "number"
                },
                "engine_temp": {
                    "type": "number"
                },
                "fuel_consumption": {
                    "type": "number"
                },
                "fuel_level": {
                    "type": "number"
                },
                "gps_lat": {
                    "type": "number"
                },
                "gps_lon": {
                    "type": "number"
                },
                "health": {
                    "type": "number"
                },
                "inverter_temp": {
                    "type": "number"
                },
                "locomotive_id": {
                    "type": "integer"
                },
                "main_reservoir_pressure": {
                    "type": "number"
                },
                "oil_pressure": {
                    "type": "number"
                },
                "oil_temp": {
                    "type": "number"
                },
                "pantograph_voltage": {
                    "type": "number"
                },
                "speed": {
                    "type": "number"
                },
                "traction_current": {
                    "type": "number"
                },
                "traction_force": {
                    "type": "number"
                },
                "traction_voltage": {
                    "type": "number"
                },
                "ts": {
                    "type": "string"
                },
                "wheel_slip": {
                    "type": "number"
                }
            }
        },
        "domain.TelemetryLimits": {
            "type": "object",
            "properties": {
                "ambient_temp_critical_max": {
                    "type": "number"
                },
                "ambient_temp_critical_min": {
                    "type": "number"
                },
                "ambient_temp_max": {
                    "type": "number"
                },
                "ambient_temp_min": {
                    "type": "number"
                },
                "ambient_temp_warning_max": {
                    "type": "number"
                },
                "ambient_temp_warning_min": {
                    "type": "number"
                },
                "battery_voltage_critical_max": {
                    "type": "number"
                },
                "battery_voltage_critical_min": {
                    "type": "number"
                },
                "battery_voltage_max": {
                    "type": "number"
                },
                "battery_voltage_min": {
                    "type": "number"
                },
                "battery_voltage_warning_max": {
                    "type": "number"
                },
                "battery_voltage_warning_min": {
                    "type": "number"
                },
                "brake_cylinder_pressure_critical_max": {
                    "type": "number"
                },
                "brake_cylinder_pressure_critical_min": {
                    "type": "number"
                },
                "brake_cylinder_pressure_max": {
                    "type": "number"
                },
                "brake_cylinder_pressure_min": {
                    "type": "number"
                },
                "brake_cylinder_pressure_warning_max": {
                    "type": "number"
                },
                "brake_cylinder_pressure_warning_min": {
                    "type": "number"
                },
                "brake_pipe_pressure_critical_max": {
                    "type": "number"
                },
                "brake_pipe_pressure_critical_min": {
                    "type": "number"
                },
                "brake_pipe_pressure_max": {
                    "type": "number"
                },
                "brake_pipe_pressure_min": {
                    "type": "number"
                },
                "brake_pipe_pressure_warning_max": {
                    "type": "number"
                },
                "brake_pipe_pressure_warning_min": {
                    "type": "number"
                },
                "engine_rpm_critical_max": {
                    "type": "number"
                },
                "engine_rpm_critical_min": {
                    "type": "number"
                },
                "engine_rpm_max": {
                    "type": "number"
                },
                "engine_rpm_min": {
                    "type": "number"
                },
                "engine_rpm_warning_max": {
                    "type": "number"
                },
                "engine_rpm_warning_min": {
                    "type": "number"
                },
                "engine_temp_critical_max": {
                    "type": "number"
                },
                "engine_temp_critical_min": {
                    "type": "number"
                },
                "engine_temp_max": {
                    "type": "number"
                },
                "engine_temp_min": {
                    "type": "number"
                },
                "engine_temp_warning_max": {
                    "type": "number"
                },
                "engine_temp_warning_min": {
                    "type": "number"
                },
                "fuel_consumption_critical_max": {
                    "type": "number"
                },
                "fuel_consumption_critical_min": {
                    "type": "number"
                },
                "fuel_consumption_max": {
                    "type": "number"
                },
                "fuel_consumption_min": {
                    "type": "number"
                },
                "fuel_consumption_warning_max": {
                    "type": "number"
                },
                "fuel_consumption_warning_min": {
                    "type": "number"
                },
                "fuel_level_critical_max": {
                    "type": "number"
                },
                "fuel_level_critical_min": {
                    "type": "number"
                },
                "fuel_level_max": {
                    "type": "number"
                },
                "fuel_level_min": {
                    "type": "number"
                },
                "fuel_level_warning_max": {
                    "type": "number"
                },
                "fuel_level_warning_min": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "inverter_temp_critical_max": {
                    "type": "number"
                },
                "inverter_temp_critical_min": {
                    "type": "number"
                },
                "inverter_temp_max": {
                    "type": "number"
                },
                "inverter_temp_min": {
                    "type": "number"
                },
                "inverter_temp_warning_max": {
                    "type": "number"
                },
                "inverter_temp_warning_min": {
                    "type": "number"
                },
                "locomotive_id": {
                    "type": "integer"
                },
                "main_reservoir_pressure_critical_max": {
                    "type": "number"
                },
                "main_reservoir_pressure_critical_min": {
                    "type": "number"
                },
                "main_reservoir_pressure_max": {
                    "type": "number"
                },
                "main_reservoir_pressure_min": {
                    "type": "number"
                },
                "main_reservoir_pressure_warning_max": {
                    "type": "number"
                },
                "main_reservoir_pressure_warning_min": {
                    "type": "number"
                },
                "oil_pressure_critical_max": {
                    "type": "number"
                },
                "oil_pressure_critical_min": {
                    "type": "number"
                },
                "oil_pressure_max": {
                    "type": "number"
                },
                "oil_pressure_min": {
                    "type": "number"
                },
                "oil_pressure_warning_max": {
                    "type": "number"
                },
                "oil_pressure_warning_min": {
                    "type": "number"
                },
                "oil_temp_critical_max": {
                    "type": "number"
                },
                "oil_temp_critical_min": {
                    "type": "number"
                },
                "oil_temp_max": {
                    "type": "number"
                },
                "oil_temp_min": {
                    "type": "number"
                },
                "oil_temp_warning_max": {
                    "type": "number"
                },
                "oil_temp_warning_min": {
                    "type": "number"
                },
                "pantograph_voltage_critical_max": {
                    "type": "number"
                },
                "pantograph_voltage_critical_min": {
                    "type": "number"
                },
                "pantograph_voltage_max": {
                    "type": "number"
                },
                "pantograph_voltage_min": {
                    "type": "number"
                },
                "pantograph_voltage_warning_max": {
                    "type": "number"
                },
                "pantograph_voltage_warning_min": {
                    "type": "number"
                },
                "speed_critical_max": {
                    "type": "number"
                },
                "speed_critical_min": {
                    "type": "number"
                },
                "speed_max": {
                    "type": "number"
                },
                "speed_min": {
                    "type": "number"
                },
                "speed_warning_max": {
                    "type": "number"
                },
                "speed_warning_min": {
                    "type": "number"
                },
                "traction_current_critical_max": {
                    "type": "number"
                },
                "traction_current_critical_min": {
                    "type": "number"
                },
                "traction_current_max": {
                    "type": "number"
                },
                "traction_current_min": {
                    "type": "number"
                },
                "traction_current_warning_max": {
                    "type": "number"
                },
                "traction_current_warning_min": {
                    "type": "number"
                },
                "traction_force_critical_max": {
                    "type": "number"
                },
                "traction_force_critical_min": {
                    "type": "number"
                },
                "traction_force_max": {
                    "type": "number"
                },
                "traction_force_min": {
                    "type": "number"
                },
                "traction_force_warning_max": {
                    "type": "number"
                },
                "traction_force_warning_min": {
                    "type": "number"
                },
                "traction_voltage_critical_max": {
                    "type": "number"
                },
                "traction_voltage_critical_min": {
                    "type": "number"
                },
                "traction_voltage_max": {
                    "type": "number"
                },
                "traction_voltage_min": {
                    "type": "number"
                },
                "traction_voltage_warning_max": {
                    "type": "number"
                },
                "traction_voltage_warning_min": {
                    "type": "number"
                },
                "wheel_slip_critical_max": {
                    "type": "number"
                },
                "wheel_slip_critical_min": {
                    "type": "number"
                },
                "wheel_slip_max": {
                    "type": "number"
                },
                "wheel_slip_min": {
                    "type": "number"
                },
                "wheel_slip_warning_max": {
                    "type": "number"
                },
                "wheel_slip_warning_min": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Locomotive Digital Twin API",
	Description:      "Real-time telemetry dashboard for locomotive dispatchers and drivers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
